// Generated by CRM App/sync/stripe_setup.py. Public Stripe payment links (safe to publish).
window.AWD_PAYMENT_LINKS = [
  {
    "key": "new_website",
    "label": "New Website",
    "detail": "$225 today ($200 site + $25 web address setup), then $50/month starting next month",
    "url": "https://buy.stripe.com/5kQ28s8854xnfEJcbJcV200"
  },
  {
    "key": "website_upgrade",
    "label": "Website Upgrade",
    "detail": "$200 today, then $50/month starting next month (keeps their web address)",
    "url": "https://buy.stripe.com/9B614o9c95BrgIN1x5cV201"
  },
  {
    "key": "website_only",
    "label": "Website Only",
    "detail": "$200 one time, no monthly fee (they run the site)",
    "url": "https://buy.stripe.com/bJe6oIcolbZP1NT8ZxcV202"
  },
  {
    "key": "website_only_domain",
    "label": "Website Only + web address",
    "detail": "$225 one time ($200 site + $25 web address setup), no monthly fee",
    "url": "https://buy.stripe.com/9B6fZi741aVL9glfnVcV203"
  }
];
